### ISSUE TITLE
can not install this APK from google play

### ISSUE THREAD

**Issue by benshi001** [ai-benchmark/ai-benchmark.github.io#1]
For some special reason, I can not install the APK from google play, could you please attach your APK to github? Thank you.

Actually I am working for a phone manufactor, whose sample phone has no google play / google service installed. But I would like to use your AI benchmark to test the performance of the sample phone NNAPI.

So could you please attach your APK to github? Thank you.

**Comment by ai-benchmark** [comment]
> So could you please attach your APK to github? Thank you.

The latest AI Benchmark APKs are now available on the project website:

https://ai-benchmark.com/download
